### ISSUE TITLE
Incorrect persist address

### ISSUE THREAD

**Issue by mdbond** [NVSL/Corundum#2]
In BuddyAlloc::open(), I think this line:

persist_obj(inner, true);

incorrectly tries to persist a stack location that lives in volatile memory, rather than the persistent BuddyAllocInner instance that it references. Instead, the line should be:

persist_obj(*inner, true);

More info: I've been modifying Corundum to use shadow memory, i.e., a volatile copy of the nonvolatile memory space, which helps to identify incorrect/missing persist calls. I've modified the persist calls to first copy the object from the volatile shadow to persistent memory. That helped to find the incorrect persist call above; I haven't found any other incorrect persist calls.

However, it seems like there are a lot of *missing* persist operations -- such that the evaluation programs don't work correctly whenever they start from an existing pool file from a previous run. The evaluation programs can be made to work correctly by explicitly copying the volatile copy's contents to the nonvolatile memory being shadowed just before program exit (when the nonvolatile memory space is dropped).

**Comment by mhoseinzadeh** [comment]
Thank you for posting an issue. I will fix the incorrect persist operation in the next version. `persist_obj(*inner, true);` is also not quite right, though. I will use a native pointer to keep the inner data.

The `persist_obj()` function attempts to `clflush` the lines corresponding to the given object. If the shadow copy keeps all cache lines, that should be fine. If there is some _missing_ persist operation that you are certain about, please reply to this post.

**Comment by mdbond** [comment]
Thanks! Unfortunately I don't know where the missing persist operations are. It's possible to check at various points during an execution whether the persistent copy of memory is up-to-date with the volatile shadow copy -- and there are a lot of out-of-date bytes, both throughout execution and at the end of a normal execution of the performance benchmarks -- but I'm not sure how to figure out where the missing persist operations are. I guess it'd be possible to find the write operations that aren't ever getting persisted, by using dynamic analysis metadata to keep track of every byte or word's first write instruction (although that'd require identifying every persistent write in the program, which is probably easy for the program's persistent writes since they all get handled by Corundum, but not so easy for persistent writes inside Corundum), or something like that.

**Comment by mhoseinzadeh** [comment]
There are many places that persist are not required because data reset on recovery such as `PMutex`, `VCell`, some parts of the allocator, parts of journaling objects, etc. So, comparing the persistent copy and the volatile shadow copy is not the best solution as long as the copying happens only in the `persist` operation.

Corundum uses undo logging for data. It creates logs for every update, persists the logs immediately after creation, and postpones persisting the update to the end of the transaction right before committing them.

The allocator uses redo logging. It collects the changes in a ring buffer (`aux`) and persists the whole buffer at once before performing the changes (this is one example that the persist operation is not necessary for every writes to the pmem).

Consequently, binging writes and persist is not the best way to check the consistency. Corundum may have some undetected bugs which I am trying to find. Unlike the implementation, the semantics are provably correct (assuming that the allocator and journaling system are flawless).

**Comment by mdbond** [comment]
Good point that some data doesn't need to be persisted for correctness. I also see your point that some writes are persisted in bulk, but I think checking the shadow consistency late (e.g., at the end of each transaction or the end of the execution) could address that issue. 

Finding missing persist operations seems like a hard problem in general, especially since running and killing the process without actually cutting the power apparently provides a "persist everything regardless of what was explicitly persisted" policy in practice. In contrast, the shadow implementation (which I'm happy to share if that'd be helpful) essentially emulates a "don't persist except by an explicit persist operation" policy. So they're kind of duals of each other.

**Comment by mhoseinzadeh** [comment]
Emulating power failure with shadow copy seems very plausible. I would be happy to check out your shadow implementation. You may also want to check how to use page-fault handling to record actual writes to pmem. You can make the pmem pages unwritable, then when the program tries to write on it, a page-fault event happens. Using that, you can record writes to the pmem.

**Comment by mdbond** [comment]
Good point about page-fault handling. Another approach (which is orthogonal to the shadow approach) would be to write a Pintool to intercept all writes and clflushes, and detect potentially missing clflushes by identifying writes that are never clflushed (either the locations are overwritten or the execution ends before a clflush).

Here's a diff of my shadow implementation against HEAD:
[shadow-diff.txt](https://github.com/NVSL/Corundum/files/6954987/shadow-diff.txt)
